//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardCRMClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardCRMClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon @__TemplateIcon {
            get {
                object obj = ResourceManager.GetObject("__TemplateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:element name=&quot;CRMContext&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;Context&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:sequence&gt;
        ///							&lt;xs:element name=&quot;EntityId&quot; type=&quot;xs:string&quot; /&gt;
        ///							&lt;xs:element name=&quot;EntityType&quot; type=&quot;xs:string&quot; /&gt;
        ///							&lt;xs:element name=&quot;Organization&quot; type=&quot;xs:string&quot; /&gt;
        ///							&lt;xs:element name=&quot;CR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRMContext {
            get {
                return ResourceManager.GetString("CRMContext", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon crmicon {
            get {
                object obj = ResourceManager.GetObject("crmicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:element name=&quot;CRMTasks&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;Task&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:sequence&gt;
        ///							&lt;xs:element name=&quot;TaskId&quot; /&gt;
        ///							&lt;xs:element name=&quot;SerialNumber&quot; /&gt;
        ///							&lt;xs:element name=&quot;DestinationUser&quot; /&gt;
        ///							&lt;xs:element name=&quot;Process&quot; /&gt;
        ///							&lt;xs:element n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRMTasks {
            get {
                return ResourceManager.GetString("CRMTasks", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap k2crmicon {
            get {
                object obj = ResourceManager.GetObject("k2crmicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Client Event Wizard.
        /// </summary>
        internal static string WizardCRMClientDescription {
            get {
                return ResourceManager.GetString("WizardCRMClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Client Event.
        /// </summary>
        internal static string WizardCRMClientDisplayName {
            get {
                return ResourceManager.GetString("WizardCRMClientDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Client Event Wizard.
        /// </summary>
        internal static string WizardCRMClientPropertyDescription {
            get {
                return ResourceManager.GetString("WizardCRMClientPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Client Event.
        /// </summary>
        internal static string WizardCRMClientPropertyDisplayName {
            get {
                return ResourceManager.GetString("WizardCRMClientPropertyDisplayName", resourceCulture);
            }
        }
    }
}
